version: "3.8"
services:
  api:
    container_name: api
    build:
      context: ./backend/api/
      dockerfile: Dockerfile.dev
      # dockerfile: Dockerfile.prod
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./backend/api:/api
        #- node_modules:/api/node_modules
        #- dist:/api/dist
    restart: on-failure
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 3001:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    restart: on-failure

  db:
    image: postgres:12.6
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ft_transcendence
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      TZ: Asia/Tokyo
    ports:
      - 5432:5432

volumes:
  node_modules:
  dist:
  postgres:
