version: "3.8"
services:
  api:
    build:
      context: ./backend/api/
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./backend/api
        target: /api
  db:
    image: postgres:12.6
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ft_transcendence
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      TZ: Asia/Tokyo
    ports:
      - 5432:5432
